package com.stellaatlas.observation.domain;

public enum ObservationReasonCode {
    MODERATE_CLOUD_COVER,
    HIGH_CLOUD_COVER,
    VERY_HIGH_CLOUD_COVER,
    MODERATE_PRECIPITATION_RISK,
    HIGH_PRECIPITATION_RISK,
    VERY_HIGH_PRECIPITATION_RISK,
    MODERATE_VISIBILITY,
    LOW_VISIBILITY,
    VERY_LOW_VISIBILITY,
    HIGH_HUMIDITY,
    VERY_HIGH_HUMIDITY,
    EXTREME_HUMIDITY,
    MODERATE_WIND,
    STRONG_WIND,
    VERY_STRONG_WIND,
    MODERATE_MOONLIGHT,
    BRIGHT_MOONLIGHT,
    VERY_BRIGHT_MOONLIGHT,
    ASTRONOMICAL_TWILIGHT,
    NAUTICAL_TWILIGHT,
    CIVIL_TWILIGHT,
    DAYLIGHT,
    IDEAL_CONDITIONS
}
